### ISSUE TITLE
Changement du propriétaire de l'app/ Change the owner of the repository

### ISSUE THREAD

**Issue by frju365** [massyas/libresonic_ynh#1]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by frju365** [comment]
Perhaps add the app in the manifest.json here : https://github.com/YunoHost/apps/blob/master/community.json to have the app listed here : https://yunohost.org/#/apps_in_progress_en

**Comment by massyas** [comment]
Bonjour,
Merci pour ce commentaire. Comment faire pour que mon app rejoigne l'organisation Yunohost-App? Merci de m'indiquer la façon de procéder.
J'ajouterai ensuite l'App dans community.json.
Merci

**Comment by frju365** [comment]
Tu dois accepter l'invitation que je t'ai envoyée pour rejoindre l'organisation **Yunohost-Apps**, et ensuite tu va dans "Settings < Change Ownership"(de ton dépôt) et là tu rentre le nom de ton dépôt et le nom de l'organisation (**Yunohost-Apps**) et tu valides. Et c'est bon, ton dépôt sera dans l'organisation. (bien-sûr ce sera toujours ton dépôt).
Si tu as un problème, n'hésites pas à le reporter ici.

**Comment by massyas** [comment]
Merci. Transfert fait et pull request envoyé pour l'ajout dans community.json.
